# Generated by Django 4.2.11 on 2024-04-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='publushed_on',
            new_name='published_on',
        ),
    ]
