# Generated by Django 4.2.11 on 2024-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_publushed_on_review_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
