# Generated by Django 4.2.11 on 2024-04-11 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(20)])),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cover_photo', models.ImageField(upload_to='cover_photos')),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
