# Generated by Django 4.2.11 on 2024-04-18 14:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smilestays_app.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), smilestays_app.common.validators.validate_starts_with_uppercase])),
                ('description', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(20)])),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cover_photo', models.ImageField(upload_to='cover_photos')),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Resort', 'Resort'), ('Villa', 'Villa'), ('Guest house', 'Guest house'), ('Hostel', 'Hostel')], max_length=11)),
                ('price_for_room_per_night', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
