# Generated by Django 4.2.11 on 2024-04-12 18:30

import django.core.validators
from django.db import migrations, models
import smilestays_app.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_for_room_per_night',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), smilestays_app.common.validators.validate_starts_with_uppercase]),
        ),
    ]
