# Generated by Django 4.2.11 on 2024-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_price_for_room_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Resort', 'Resort'), ('Villa', 'Villa'), ('Guest house', 'Guest house'), ('Hostel', 'Hostel')], default='Hotel', max_length=11),
            preserve_default=False,
        ),
    ]
