# Generated by Django 4.2.11 on 2024-04-15 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
